name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - numpy
  - matplotlib
  - lxml
  - plotly
  - plotly[express]
  - pandas
  - dayplot
  - pydantic
  - requests
  - nbformat
  - pyarrow
  - wordcloud
  - altair
  - venn
  - xlsxwriter
  - python-calamine
  - xeus-r
  - r-knitr
  - r-dplyr
  - r-vroom
  - r-ggplot2